/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorround;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author HP
 */
class calci extends javax.swing.JFrame {

    /**
     * Creates new form calci
     */
    double firstnum=Double.MAX_VALUE;
    double secondnum;
    double result=Double.MAX_VALUE;
    String operation=" ";
    public calci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText = new javax.swing.JTextField();
        jBtn8 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnEqual = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtnSubt = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextActionPerformed(evt);
            }
        });
        getContentPane().add(jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 312, 47));

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 61));

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 61));

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 61));

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, 61));

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 61));

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, 61));

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 70, 61));

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 61));

        jBtnDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDot.setText(".");
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, 61));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setText("+/");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 70, 61));

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 70, 61));

        jBtnEqual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEqual.setText("=");
        jBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 70, 61));

        jBtnMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, 60));

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 70, 61));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton15.setText("jButton1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 61));

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 70, 61));

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, 61));

        jBtnSubt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSubt.setText("-");
        jBtnSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, 61));

        jBtnDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 70, 61));

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnBack.setText("<-");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 61));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        // TODO add your handling code here:" 
        String number;
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        if(operation==" ")
        {
            number=jBtn8.getText();
            operation="1";
        }
        else
          number=jText.getText()+jBtn8.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        // TODO add your handling code here:
       String number;
       if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        if(operation==" ")
            number=jBtn7.getText();
        else
          number=jText.getText()+jBtn7.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        // TODO add your handling code here:
        String number;
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        if(operation==" ")
        {
            number=jBtn4.getText();
            operation="1";
        }
        else
         number=jText.getText()+jBtn4.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        // TODO add your handling code here:
         String number;
         if(jText.getText()=="Invalid Input")
            jText.setText(" ");
         if(operation==" ")
         {
            number=jBtn5.getText();
            operation="1";
         }
         else
                 number=jText.getText()+jBtn5.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        // TODO add your handling code here:
         String number;
         if(jText.getText()=="Invalid Input")
            jText.setText(" ");
         if(operation==" ")
         {
            number=jBtn1.getText();
            operation="1";
         }
         else
           number=jText.getText()+jBtn1.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:
        jText.setText(" ");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        // TODO add your handling code here:
         String number;
         if(jText.getText()=="Invalid Input")
            jText.setText(" ");
         if(operation==" ")
         {
            number=jBtn9.getText();
            operation="1";
         }
         else
          number=jText.getText()+jBtn9.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        // TODO add your handling code here:
        String number;
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        if(operation==" ")
        {
            number=jBtn0.getText();
           operation="1";
        }
        else
          number=jText.getText()+jBtn0.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
        // TODO add y++++++++++++++++++++our handling code here:
        if(!jText.getText().contains("."))
        {
            jText.setText(jText.getText()+jBtnDot.getText());
            operation="1";
        }
        
    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Double d=Double.parseDouble(jText.getText());
        d=d*(-1);
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        jText.setText(String.valueOf(d));
       
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jText.getText());
        jText.setText(" ");
        operation="+";
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualActionPerformed
        String ans=null; 
        try
        {
        secondnum= Double.parseDouble(jText.getText());
        }
        catch(Exception e)
        {
            operation=" ";
        }
       switch(operation)
       {
           case "+" : result=firstnum+secondnum;
                       break;
           case "*" :  result= firstnum*secondnum;
                          break;
           case "-" :   result=firstnum-secondnum;
                           break;
           case "/" :    if(secondnum!=0)
                             result=firstnum/secondnum;
                          else
                           ans="Invalid Input";
                             break;
           default :         ans="Invalid Input";
       }
       if(ans==null)
       {
           ans=String.format("%.2f",result);
           
       }
       jText.setText(ans);
       operation=" ";
    }//GEN-LAST:event_jBtnEqualActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jText.getText());
        jText.setText(" ");
        operation="*";
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        // TODO add your handling code here:
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
         String number;
         if(operation==" ")
         {
              number=jBtn6.getText();
              operation="1";
         }
         else
           number=jText.getText()+jBtn6.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        // TODO add your handling code here:
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
         String  number;
         if(operation==" ")
         {
             number=jBtn3.getText();
             operation="1";
         }
          else       
          number=jText.getText()+jBtn3.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        // TODO add your handling code here:
        if(jText.getText()=="Invalid Input")
            jText.setText(" ");
        
         String number;
         if(operation==" ")
         {
             number=jBtn2.getText();
             operation="1";
         }
          else       
          number=jText.getText()+jBtn2.getText();
         jText.setText(number);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtnSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jText.getText());
        jText.setText(" ");
        operation="-";
    }//GEN-LAST:event_jBtnSubtActionPerformed
    private void jsoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jText.getText());
        jText.setText(" ");
        operation="-";
    }//GEN-LA

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jText.getText());
        jText.setText(" ");
        operation="/";
        
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(jText.getText().length()>0)
        {
            StringBuilder strb=new StringBuilder(jText.getText());
            strb.deleteCharAt(jText.getText().length()-1);
            backspace=strb.toString();
            jText.setText(backspace);
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEqual;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnSubt;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
}
